import { useState } from 'react'

export default function ReportsPage() {
  const [reports] = useState([
    { title: 'Weekly Performance Review', date: 'Oct 24, 2023', size: '12.4 MB', status: 'Ready' },
    { title: 'Monthly Deep Dive: Q3 Ops', date: 'Oct 20, 2023', size: '45.1 MB', status: 'Ready' },
    { title: 'Q2 Fiscal Summary', date: 'Sep 30, 2023', size: '8.2 MB', status: 'Ready' },
  ])
  const [showArchive, setShowArchive] = useState(false)
  const [downloadToast, setDownloadToast] = useState(null)
  const [shareToast, setShareToast] = useState(null)
  const [showScheduleModal, setShowScheduleModal] = useState(false)
  const [scheduleDay, setScheduleDay] = useState('Monday')
  const [scheduleTime, setScheduleTime] = useState('08:00')
  const [scheduleSaved, setScheduleSaved] = useState(false)

  const handleDownload = (report) => {
    setDownloadToast(report.title)
    // Simulate download by creating a text blob
    const content = `Analyst Pro Report\n==================\n\nTitle: ${report.title}\nGenerated: ${report.date}\nSize: ${report.size}\n\n--- AI-Generated Summary ---\nThis report contains automated analysis of your organizational data.\nKey findings and recommendations are summarized below.\n\n[Full analysis would be generated from your uploaded datasets]`
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${report.title.replace(/\s+/g, '_')}.txt`
    a.click()
    URL.revokeObjectURL(url)
    setTimeout(() => setDownloadToast(null), 3000)
  }

  const handleShare = (report) => {
    const shareText = `Check out the "${report.title}" report generated by Analyst Pro on ${report.date}.`
    if (navigator.clipboard) {
      navigator.clipboard.writeText(shareText)
      setShareToast(report.title)
      setTimeout(() => setShareToast(null), 3000)
    }
  }

  const handleSaveSchedule = () => {
    setScheduleSaved(true)
    setTimeout(() => {
      setShowScheduleModal(false)
      setScheduleSaved(false)
    }, 1500)
  }

  const archivedReports = [
    { title: 'Annual Performance Review 2022', date: 'Jan 15, 2023', size: '82.1 MB', status: 'Archived' },
    { title: 'H2 Strategic Planning Deck', date: 'Dec 01, 2022', size: '34.7 MB', status: 'Archived' },
    { title: 'Customer Churn Analysis', date: 'Nov 10, 2022', size: '18.3 MB', status: 'Archived' },
  ]

  return (
    <div className="space-y-6" id="reports-page">
      {/* Toast Notifications */}
      {downloadToast && (
        <div className="fixed top-20 right-8 z-50 p-4 bg-surface-container-low rounded-md shadow-elevation-3 border border-tertiary/20 flex items-center gap-3 animate-slide-up">
          <span className="material-symbols-outlined text-[20px] text-tertiary">check_circle</span>
          <p className="text-body-sm text-on-surface font-body">Downloading "{downloadToast}"</p>
        </div>
      )}
      {shareToast && (
        <div className="fixed top-20 right-8 z-50 p-4 bg-surface-container-low rounded-md shadow-elevation-3 border border-primary/20 flex items-center gap-3 animate-slide-up">
          <span className="material-symbols-outlined text-[20px] text-primary">content_copy</span>
          <p className="text-body-sm text-on-surface font-body">Share link copied for "{shareToast}"</p>
        </div>
      )}

      {/* Schedule Modal */}
      {showScheduleModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm animate-fade-in">
          <div className="bg-surface-container-low rounded-lg p-6 w-[400px] shadow-elevation-3 animate-slide-up">
            <h3 className="font-display text-headline-sm text-on-surface mb-4">Edit Report Schedule</h3>
            <div className="space-y-4">
              <div>
                <label className="text-label-md text-on-surface-variant font-body block mb-1.5">Day</label>
                <select
                  value={scheduleDay}
                  onChange={(e) => setScheduleDay(e.target.value)}
                  className="w-full px-3 py-2.5 bg-surface-container-highest rounded-md text-body-sm text-on-surface font-body outline-none border border-outline-variant/20 focus:border-primary/40"
                >
                  {['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'].map(d => (
                    <option key={d} value={d}>{d}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="text-label-md text-on-surface-variant font-body block mb-1.5">Time</label>
                <input
                  type="time"
                  value={scheduleTime}
                  onChange={(e) => setScheduleTime(e.target.value)}
                  className="w-full px-3 py-2.5 bg-surface-container-highest rounded-md text-body-sm text-on-surface font-body outline-none border border-outline-variant/20 focus:border-primary/40"
                />
              </div>
            </div>
            <div className="flex items-center justify-end gap-3 mt-6">
              <button onClick={() => setShowScheduleModal(false)} className="btn-ghost text-label-md py-2 px-4">Cancel</button>
              <button onClick={handleSaveSchedule} className="btn-primary text-label-md py-2 px-4">
                {scheduleSaved ? '✓ Saved!' : 'Save Schedule'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Header */}
      <div className="animate-slide-up">
        <h2 className="font-display text-headline-md text-on-surface mb-2">Automated Insights</h2>
        <p className="text-body-md text-on-surface-variant font-body">AI-driven narrative of your organizational health.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Main Content */}
        <div className="lg:col-span-2 space-y-6">
          {/* Latest AI Narrative */}
          <div className="ai-insight-card p-6 animate-slide-up" id="ai-narrative">
            <div className="flex items-center gap-2 mb-4">
              <span className="material-symbols-outlined text-[20px] text-secondary">auto_awesome</span>
              <h3 className="font-display text-title-lg text-on-surface">Latest AI Narrative</h3>
              <span className="text-label-sm text-outline font-body ml-auto">Analysis completed 2 hours ago</span>
            </div>

            <div className="mb-5">
              <h4 className="font-display text-title-md text-error mb-2 flex items-center gap-2">
                <span className="material-symbols-outlined text-[18px]">trending_up</span>
                Unusual Growth Spike
              </h4>
              <p className="text-body-md text-on-surface-variant font-body leading-relaxed">
                Our models detected a <strong className="text-on-surface">24.3% deviation</strong> from the projected baseline
                in the Pacific-Northwest sector. This correlates with the recent seasonal shift and a 12% drop in competitor ad-spend.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              <div className="p-4 bg-surface-container rounded-md" style={{ borderLeft: '3px solid #00e1ae' }}>
                <span className="text-label-md text-tertiary font-body">Recommendation</span>
                <p className="text-body-sm text-on-surface-variant font-body mt-1">
                  Increase inventory buffers for Q3 based on current velocity trends.
                </p>
              </div>
              <div className="p-4 bg-surface-container rounded-md" style={{ borderLeft: '3px solid #00daf3' }}>
                <span className="text-label-md text-primary font-body">Opportunity</span>
                <p className="text-body-sm text-on-surface-variant font-body mt-1">
                  Consolidate underperforming nodes to save approx. $12k/mo.
                </p>
              </div>
            </div>
          </div>

          {/* Generated Reports */}
          <div className="bg-surface-container-low rounded-md p-6 animate-slide-up" id="generated-reports">
            <h3 className="font-display text-headline-sm text-on-surface mb-5">Generated Reports</h3>
            <div className="space-y-3">
              {reports.map((report, i) => (
                <div
                  key={i}
                  className="flex items-center gap-4 p-4 bg-surface-container rounded-md hover:bg-surface-container-high transition-colors group"
                  id={`report-${i}`}
                >
                  <div className="w-10 h-10 rounded-lg bg-surface-container-highest flex items-center justify-center group-hover:bg-primary/10 transition-colors">
                    <span className="material-symbols-outlined text-[20px] text-primary">description</span>
                  </div>
                  <div className="flex-1">
                    <h4 className="text-title-md text-on-surface font-display">{report.title}</h4>
                    <p className="text-label-sm text-on-surface-variant font-body mt-0.5">
                      Generated: {report.date} • {report.size}
                    </p>
                  </div>
                  <div className="flex items-center gap-3">
                    <span className="text-label-sm text-tertiary font-body">{report.status}</span>
                    <button onClick={() => handleDownload(report)} className="p-2 rounded-lg hover:bg-primary/10 transition-colors" title="Download Report">
                      <span className="material-symbols-outlined text-[18px] text-on-surface-variant hover:text-primary transition-colors">download</span>
                    </button>
                    <button onClick={() => handleShare(report)} className="p-2 rounded-lg hover:bg-primary/10 transition-colors" title="Copy Share Link">
                      <span className="material-symbols-outlined text-[18px] text-on-surface-variant hover:text-primary transition-colors">ios_share</span>
                    </button>
                  </div>
                </div>
              ))}
            </div>

            {/* Archive Toggle */}
            <button onClick={() => setShowArchive(!showArchive)} className="btn-ghost w-full mt-4 text-label-md">
              <span className="material-symbols-outlined text-[16px] mr-1">{showArchive ? 'expand_less' : 'inventory_2'}</span>
              {showArchive ? 'Hide Archive' : 'Full Archive'}
            </button>

            {/* Archived Reports */}
            {showArchive && (
              <div className="space-y-3 mt-4 pt-4 border-t border-outline-variant/10 animate-slide-up">
                {archivedReports.map((report, i) => (
                  <div key={i} className="flex items-center gap-4 p-4 bg-surface-container rounded-md opacity-70 hover:opacity-100 transition-opacity">
                    <div className="w-10 h-10 rounded-lg bg-surface-container-highest flex items-center justify-center">
                      <span className="material-symbols-outlined text-[20px] text-outline">archive</span>
                    </div>
                    <div className="flex-1">
                      <h4 className="text-title-md text-on-surface font-display">{report.title}</h4>
                      <p className="text-label-sm text-on-surface-variant font-body mt-0.5">
                        {report.date} • {report.size}
                      </p>
                    </div>
                    <span className="text-label-sm text-outline font-body">{report.status}</span>
                    <button onClick={() => handleDownload(report)} className="p-2 rounded-lg hover:bg-primary/10 transition-colors" title="Download">
                      <span className="material-symbols-outlined text-[18px] text-on-surface-variant">download</span>
                    </button>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Right Sidebar */}
        <div className="space-y-4">
          {/* Core Index */}
          <div className="bg-surface-container-low rounded-md p-5 animate-slide-up">
            <h3 className="font-display text-title-lg text-on-surface mb-4">Core Index</h3>
            <div className="space-y-3">
              {[
                { label: 'Revenue Health', value: 92, color: 'bg-tertiary' },
                { label: 'Growth Velocity', value: 78, color: 'bg-primary' },
                { label: 'Operational Efficiency', value: 85, color: 'bg-secondary' },
              ].map((item, i) => (
                <div key={i}>
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-body-sm text-on-surface-variant font-body">{item.label}</span>
                    <span className="text-label-md text-on-surface font-body">{item.value}%</span>
                  </div>
                  <div className="w-full h-1.5 bg-surface-container-highest rounded-full overflow-hidden">
                    <div className={`h-full ${item.color} rounded-full transition-all duration-700`} style={{ width: `${item.value}%` }}></div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Schedule */}
          <div className="bg-surface-container-low rounded-md p-5 animate-slide-up">
            <h3 className="font-display text-title-lg text-on-surface mb-4 flex items-center gap-2">
              <span className="material-symbols-outlined text-[18px] text-primary">schedule</span>
              Active Schedule
            </h3>
            <div className="p-3 bg-surface-container rounded-md">
              <p className="text-title-md text-on-surface font-display">Weekly Sync</p>
              <p className="text-body-sm text-on-surface-variant font-body mt-1">
                Every {scheduleDay} at {scheduleTime}
              </p>
            </div>
            <button onClick={() => setShowScheduleModal(true)} className="btn-ghost w-full mt-3 text-label-md">Edit Schedule</button>
          </div>
        </div>
      </div>
    </div>
  )
}
